### ISSUE TITLE
Errors on MacOS with ZSH

### ISSUE THREAD

**Issue by uhlhosting** [yuzutech/kroki-cli#23] opened 2021-10-18 20:44 UTC
```
22:42:55 [cosmic:~] % echo "eNpKyUwvSizIUHBXqPZIzcnJ17ULzy_KSakFBAAA__9sQAjG" | kroki decode -
digraph G {Hello->World}
zsh: parse error near `}'
22:43:11 [cosmic:~] 1 % $ echo "eNpKyUwvSizIUHBXqPZIzcnJ17ULzy_KSakFBAAA__9sQAjG" | kroki decode -
digraph G {Hello->World}

zsh: parse error near `}'
22:43:20 [cosmic:~] 1 % $ echo "eNpKyUwvSizIUHBXqPZIzcnJ17ULzy_KSakFBAAA__9sQAjG" | kroki decode - digraph G {Hello->World}

zsh: parse error near `}'
```

**Comment by ggrossetie** [comment] 2021-10-19 06:00
Just to be sure, you are only executing the first part, right?

```
echo "eNpKyUwvSizIUHBXqPZIzcnJ17ULzy_KSakFBAAA__9sQAjG" | kroki decode -
```

The following is the output of the command:

```
digraph G {Hello->World}
```

I cannot reproduce this issue on similar environment unless I try to execute `digraph G {Hello->World}` as part of the command (which is an invalid command, hence the error).

**Comment by ggrossetie** [comment] 2022-07-02 11:32
Closing since I cannot reproduce this issue and no additional information was provided.

**Closed as completed by ggrossetie** 2022-07-02 11:32 UTC
Labels: question
